from app.routers.v1.agent_internal_router import router as agent_internal_router
from app.routers.v1.animal_router import router as animal_router
from app.routers.v1.anthropic_chat_router import router as anthropic_chat_router
from app.routers.v1.auth_router import router as auth_router
from app.routers.v1.document_router import router as document_router
from app.routers.v1.health_log_router import router as health_log_router
from app.routers.v1.image_router import router as image_router
from app.routers.v1.internal_router import router as internal_router
from app.routers.v1.permission_router import router as permission_router
from app.routers.v1.resource_router import router as resource_router
from app.routers.v1.role_router import router as role_router
from app.routers.v1.stripe_router import router as stripe_router
from app.routers.v1.users_router import router as users_router
