from app.core.prompts.system_prompt import (
    CHAT_DOCUMENTS_TEMPLATE,
    GET_INVOICES_TOOL_DESCRIPTION,
    SEARCH_DOCUMENTS_TOOL_DESCRIPTION,
    SYSTEM_PROMPT,
    WEB_SEARCH_TOOL_DESCRIPTION,
)
