"""

Revision ID: 756d89c6635f
Revises: 9ec6510b3a0d
Create Date: 2026-07-27 13:36:30.454863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756d89c6635f'
down_revision: Union[str, Sequence[str], None] = '9ec6510b3a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_health_logs',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('health_log_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['health_log_id'], ['healthlogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id', 'health_log_id')
    )
    op.drop_constraint(op.f('invoices_health_log_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'health_log_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('health_log_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('invoices_health_log_id_fkey'), 'invoices', 'healthlogs', ['health_log_id'], ['id'], ondelete='CASCADE')
    op.drop_table('invoice_health_logs')
    # ### end Alembic commands ###
